import manifest from './media-manifest.json';

// Generated by scripts/build-media.mjs from the originals in assets-src/.
export type MediaAsset = {
  width: number;
  height: number;
  src: string;
  avif: string;
  webp: string;
  placeholder?: string;
};

export type MediaKey = keyof typeof manifest;

export const media: Record<MediaKey, MediaAsset> = manifest;
